#!/usr/bin/env node
'use strict'
/**
 * Installs SandLoader into whatever attach point this build offers.
 *
 * On **Steam** the game loads a mod loader itself: it scans
 * `steamapps/workshop/content/2764460/<any>/` for a `modinfo.json` whose
 * `modID` is "fluxloader", then requires `fluxloader.bundle.js` beside it.
 * Those two names are the game's ABI, not a dependency on any particular
 * loader project - SandLoader simply occupies the slot. Nothing inside the
 * game directory is touched and a Steam file verification stays green.
 *
 * On **GOG and other non-Steam builds** that scan never runs (the game's own
 * main.js opens it with `if (PLATFORM_NAME !== 'steam') return null`). There
 * the installer adds a `resources/app/` directory beside the untouched
 * `app.asar`: Electron resolves `app` before `app.asar`, so our three-file
 * bootstrap loads first. No original file is modified, and uninstalling
 * deletes the directory again. See src/asar/platform.js for the full
 * reasoning and the honest trade-offs.
 *
 * **Microsoft Store and Game Pass are not supported.** The package lives under
 * WindowsApps, which denies writes even to administrators and verifies its own
 * signature; there is no additive file we may place and no non-destructive way
 * in. The installer says so rather than pretending.
 *
 * Usage:
 *   node install.js              install / update
 *   node install.js --status     report what is currently installed
 *   node install.js --uninstall  remove whatever was installed
 */

const fs = require('fs')
const path = require('path')

const locate = require('./src/asar/locate')
const platform = require('./src/asar/platform')

const SLOT = 'smln'
const BUNDLE = 'fluxloader.bundle.js'
const MODINFO = 'modinfo.json'
const APP_DIR = 'app'

function say(...a) { console.log(...a) }
function fail(msg, hint) {
  console.error('\n  ERROR  ' + msg)
  if (hint) console.error('         ' + String(hint).split('\n').join('\n         '))
  process.exitCode = 1
}

// ------------------------------------------------------------- Steam slot

/** The tiny file the game requires. It just points at this checkout. */
function shimSource(entryPath) {
  const target = entryPath.replace(/\\/g, '\\\\')
  return `'use strict'
/*
 * SandLoader slot shim - generated by install.js, do not edit.
 * The real loader lives in the SandLoader project directory referenced below,
 * so editing its sources takes effect on the next launch with no reinstall.
 */
module.exports = require('${target}')
`
}

function modinfoSource(version) {
  return JSON.stringify({
    modID: 'fluxloader',
    name: 'SandLoader',
    shortName: 'SandLoader',
    version,
    description:
      'Mod loader for Sandustry. Occupies the loader slot the game exposes; ' +
      'patches the renderer bundle in memory and never modifies game files.',
    author: 'SandLoader',
  }, null, 2) + '\n'
}

function resolveSlotDir() {
  const dir = locate.workshopDir()
  if (!dir) return null
  return path.join(dir, SLOT)
}

// ------------------------------------------------------- non-Steam bootstrap

/**
 * The stub Electron actually runs. It does nothing but hand over to the
 * checkout, so editing SandLoader's sources needs no reinstall - the same
 * property the Steam shim has.
 */
function bootstrapStub(bootPath) {
  const target = bootPath.replace(/\\/g, '\\\\')
  return `'use strict'
/*
 * SandLoader bootstrap - generated by install.js, do not edit.
 *
 * Electron resolves its app package by searching resources/ for 'app' before
 * 'app.asar', so this directory loads instead of the game's - and then hands
 * control straight back to it. The original app.asar is never modified.
 */
require('${target}').boot()
`
}

/**
 * `package.json` for the added directory. Mirrors the real app's name and
 * version so anything reading `app.getName()` / `app.getVersion()` still sees
 * the right values.
 */
function bootstrapPackage(realPkg, version) {
  return JSON.stringify({
    name: (realPkg && realPkg.name) || 'sandustry',
    version: (realPkg && realPkg.version) || '0.0.0',
    description: (realPkg && realPkg.description) || 'Sandustry game',
    main: 'smln-bootstrap.js',
    smlnBootstrap: version,
  }, null, 2) + '\n'
}

function receiptSource(install, version) {
  return JSON.stringify({
    loader: 'SandLoader',
    version,
    loaderPath: path.resolve(__dirname),
    installedAt: new Date().toISOString(),
    gameVersion: install.version,
    note: 'Delete this directory to uninstall. No original game file was modified.',
  }, null, 2) + '\n'
}

/** Read the real app's package.json out of the untouched archive. */
function realPackage(install) {
  try {
    const reader = require('./src/asar/reader')
    const archive = reader.open(install.asar)
    try { return archive.readJson('package.json') } finally { archive.close() }
  } catch (_) { return null }
}

function installBootstrap(install, plat, version) {
  const appDir = path.join(plat.resources, APP_DIR)

  if (plat.hasExistingAppDir && !plat.ourAppDir) {
    fail(`${appDir} already exists and is not ours.`,
      'Something else is attached here. Refusing to overwrite it - remove that first if you\n' +
      'are sure it is no longer needed.')
    return false
  }

  const bootPath = path.resolve(__dirname, 'src', 'boot', 'bootstrap.js')
  try {
    fs.mkdirSync(appDir, { recursive: true })
    fs.writeFileSync(path.join(appDir, 'package.json'), bootstrapPackage(realPackage(install), version))
    fs.writeFileSync(path.join(appDir, 'smln-bootstrap.js'), bootstrapStub(bootPath))
    fs.writeFileSync(path.join(appDir, platform.RECEIPT), receiptSource(install, version))
  } catch (e) {
    if (e.code === 'EACCES' || e.code === 'EPERM') {
      fail('no permission to write into the game directory.',
        'Run this terminal as Administrator. Target was:\n' + appDir)
    } else {
      fail('bootstrap install failed: ' + e.message)
    }
    return false
  }

  say('  bootstrap ' + appDir)
  say('  loader    ' + bootPath)
  say('\n  Installed. The original app.asar was not touched; these three files were added:')
  for (const f of platform.BOOTSTRAP_FILES) say('    ' + path.join(appDir, f))
  say('\n  Uninstall with: node install.js --uninstall\n')
  return true
}

function uninstallBootstrap(plat) {
  const appDir = path.join(plat.resources, APP_DIR)
  if (!fs.existsSync(appDir)) return false
  if (!fs.existsSync(path.join(appDir, platform.RECEIPT))) {
    fail(`${appDir} exists but has no SandLoader receipt.`,
      'Refusing to delete a directory we did not create.')
    return false
  }
  try {
    fs.rmSync(appDir, { recursive: true, force: true })
    say('\n  Removed ' + appDir)
    say('  The game is back to its original files.\n')
    return true
  } catch (e) {
    fail('could not remove ' + appDir + ': ' + e.message)
    return false
  }
}

// ------------------------------------------------------------------ status

function status() {
  const found = locate.tryLocate()
  say('\nSandustry')
  if (found.ok) {
    say('  install   ' + found.install.root)
    say('  version   ' + found.install.version + '  (found via ' + found.install.source + ')')
  } else {
    say('  install   NOT FOUND')
    say('            ' + String(found.error))
    if (found.error.detail && found.error.detail.tried) {
      for (const t of found.error.detail.tried) say('              tried ' + t)
    }
    return
  }

  const plat = platform.detect(found.install)
  const strat = platform.strategyFor(plat)
  say('\nPlatform')
  for (const line of platform.describe(plat, strat).split('\n')) say('  ' + line)

  say('\nSandLoader')
  if (strat.id === platform.STRATEGIES.WORKSHOP_SLOT) {
    const slot = resolveSlotDir()
    if (!slot) {
      say('  status    NO STEAM WORKSHOP FOLDER')
      say('            Launch the game once, or create')
      say('            steamapps/workshop/content/' + locate.APP_ID + ' manually.')
      return
    }
    say('  path      ' + slot)
    if (fs.existsSync(path.join(slot, BUNDLE))) {
      say('  status    INSTALLED')
      try {
        const info = JSON.parse(fs.readFileSync(path.join(slot, MODINFO), 'utf8'))
        say('  version   ' + info.version + '  (modID: ' + info.modID + ')')
      } catch (_) { say('  modinfo   unreadable') }
    } else {
      say('  status    not installed')
    }
    return
  }

  if (strat.id === platform.STRATEGIES.APP_BOOTSTRAP) {
    const appDir = path.join(plat.resources, APP_DIR)
    say('  path      ' + appDir)
    if (plat.ourAppDir) {
      say('  status    INSTALLED')
      try {
        const r = JSON.parse(fs.readFileSync(path.join(appDir, platform.RECEIPT), 'utf8'))
        say('  version   ' + r.version)
        say('  loader    ' + r.loaderPath)
        say('  since     ' + r.installedAt)
      } catch (_) { say('  receipt   unreadable') }
    } else {
      say('  status    not installed')
    }
    return
  }

  say('  status    UNSUPPORTED ON THIS BUILD')
  say('            ' + strat.reason.split('. ').join('.\n            '))
}

// ----------------------------------------------------------------- install

function install() {
  const found = locate.tryLocate()
  if (!found.ok) {
    fail('could not find Sandustry.', 'Set SANDUSTRY_DIR to the folder containing Sandustry.exe and retry.')
    return
  }
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8'))
  say('\n  game      ' + found.install.name + ' ' + found.install.version)
  say('  at        ' + found.install.root)

  const plat = platform.detect(found.install)
  const strat = platform.strategyFor(plat)
  say('  platform  ' + plat.kind + ' (' + plat.confidence + ')' +
    (plat.evidence.length ? '  -  ' + plat.evidence[0] : ''))

  if (!strat.supported) {
    fail('SandLoader cannot attach to this build.', strat.reason)
    return
  }

  if (strat.id === platform.STRATEGIES.APP_BOOTSTRAP) {
    say('  attach    ' + strat.id)
    installBootstrap(found.install, plat, pkg.version)
    return
  }

  // --- Steam: the loader slot
  const workshop = locate.workshopDir()
  if (!workshop) {
    fail('no Steam Workshop content folder for app ' + locate.APP_ID + '.',
      'The game only loads a mod loader on Steam. Launch the game once, or create\n' +
      'steamapps/workshop/content/' + locate.APP_ID + ' manually, then retry.')
    return
  }

  const slot = path.join(workshop, SLOT)
  const entry = path.resolve(__dirname, 'src', 'main', 'entry.js')

  try {
    fs.mkdirSync(slot, { recursive: true })
    fs.writeFileSync(path.join(slot, MODINFO), modinfoSource(pkg.version))
    fs.writeFileSync(path.join(slot, BUNDLE), shimSource(entry))
  } catch (e) {
    if (e.code === 'EACCES' || e.code === 'EPERM') {
      fail('no permission to write into the Steam workshop folder.',
        'Run this terminal as Administrator, or move your Steam library out of\n' +
        'Program Files. Target was:\n' + slot)
    } else {
      fail('install failed: ' + e.message)
    }
    return
  }

  say('  slot      ' + slot)
  say('  loader    ' + entry)
  say('\n  Installed. Start Sandustry and press ^ (or F1) to open the console.')
  say('  Nothing in the game directory was modified.\n')
}

function uninstall() {
  const found = locate.tryLocate()
  let removed = false

  const slot = resolveSlotDir()
  if (slot && fs.existsSync(slot)) {
    try {
      fs.rmSync(slot, { recursive: true, force: true })
      say('\n  Removed ' + slot)
      removed = true
    } catch (e) {
      fail('could not remove ' + slot + ': ' + e.message)
    }
  }

  if (found.ok) {
    const plat = platform.detect(found.install)
    if (uninstallBootstrap(plat)) removed = true
  }

  if (!removed) say('\n  Nothing to remove.\n')
}

const arg = process.argv[2]
if (arg === '--status' || arg === '-s') status()
else if (arg === '--uninstall' || arg === '-u') uninstall()
else install()
