#!/usr/bin/env node
'use strict'
/**
 * Installs SandLoader into the game's own loader slot.
 *
 * Sandustry scans `steamapps/workshop/content/2764460/<any>/` for a
 * `modinfo.json` whose `modID` is "fluxloader", then requires
 * `fluxloader.bundle.js` beside it. Those two names are the game's ABI, not a
 * dependency on any particular loader project - SandLoader simply occupies the slot.
 *
 * Nothing inside the game directory is modified. Uninstalling is deleting one
 * folder, and a Steam file verification stays green either way.
 *
 * Usage:
 *   node install.js              install / update
 *   node install.js --status     report what is currently installed
 *   node install.js --uninstall  remove the slot folder
 */

const fs = require('fs')
const path = require('path')

const locate = require('./src/asar/locate')

const SLOT = 'smln'
const BUNDLE = 'fluxloader.bundle.js'
const MODINFO = 'modinfo.json'

function say(...a) { console.log(...a) }
function fail(msg, hint) {
  console.error('\n  ERROR  ' + msg)
  if (hint) console.error('         ' + hint)
  process.exitCode = 1
}

/** The tiny file the game requires. It just points at this checkout. */
function shimSource(entryPath) {
  const target = entryPath.replace(/\\/g, '\\\\')
  return `'use strict'
/*
 * SandLoader slot shim - generated by install.js, do not edit.
 * The real loader lives in the SandLoader project directory referenced below,
 * so editing its sources takes effect on the next launch with no reinstall.
 */
module.exports = require('${target}')
`
}

function modinfoSource(version) {
  return JSON.stringify({
    modID: 'fluxloader',
    name: 'SandLoader',
    shortName: 'SandLoader',
    version,
    description:
      'Mod loader for Sandustry. Occupies the loader slot the game exposes; ' +
      'patches the renderer bundle in memory and never modifies game files.',
    author: 'SandLoader',
  }, null, 2) + '\n'
}

function resolveSlotDir() {
  const dir = locate.workshopDir()
  if (!dir) return null
  return path.join(dir, SLOT)
}

function status() {
  const found = locate.tryLocate()
  say('\nSandustry')
  if (found.ok) {
    say('  install   ' + found.install.root)
    say('  version   ' + found.install.version + '  (found via ' + found.install.source + ')')
  } else {
    say('  install   NOT FOUND')
    say('            ' + String(found.error))
    if (found.error.detail && found.error.detail.tried) {
      for (const t of found.error.detail.tried) say('              tried ' + t)
    }
  }

  const slot = resolveSlotDir()
  say('\nSandLoader slot')
  if (!slot) {
    say('  status    NO STEAM WORKSHOP FOLDER')
    say('            The game only scans for a loader on Steam. Without')
    say('            steamapps/workshop/content/' + locate.APP_ID + ' there is no slot to fill.')
    return
  }
  say('  path      ' + slot)
  const bundle = path.join(slot, BUNDLE)
  if (fs.existsSync(bundle)) {
    say('  status    INSTALLED')
    try {
      const info = JSON.parse(fs.readFileSync(path.join(slot, MODINFO), 'utf8'))
      say('  version   ' + info.version + '  (modID: ' + info.modID + ')')
    } catch (_) { say('  modinfo   unreadable') }
  } else {
    say('  status    not installed')
  }
}

function install() {
  const found = locate.tryLocate()
  if (!found.ok) {
    fail('could not find Sandustry.', 'Set SANDUSTRY_DIR to the folder containing Sandustry.exe and retry.')
    return
  }
  say('\n  game      ' + found.install.name + ' ' + found.install.version)
  say('  at        ' + found.install.root)

  const workshop = locate.workshopDir()
  if (!workshop) {
    fail('no Steam Workshop content folder for app ' + locate.APP_ID + '.',
      'The game only loads a mod loader on Steam. Launch the game once, or create\n' +
      '         steamapps/workshop/content/' + locate.APP_ID + ' manually, then retry.')
    return
  }

  const slot = path.join(workshop, SLOT)
  const entry = path.resolve(__dirname, 'src', 'main', 'entry.js')
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8'))

  try {
    fs.mkdirSync(slot, { recursive: true })
    fs.writeFileSync(path.join(slot, MODINFO), modinfoSource(pkg.version))
    fs.writeFileSync(path.join(slot, BUNDLE), shimSource(entry))
  } catch (e) {
    if (e.code === 'EACCES' || e.code === 'EPERM') {
      fail('no permission to write into the Steam workshop folder.',
        'Run this terminal as Administrator, or move your Steam library out of\n' +
        '         Program Files. Target was:\n         ' + slot)
    } else {
      fail('install failed: ' + e.message)
    }
    return
  }

  say('  slot      ' + slot)
  say('  loader    ' + entry)
  say('\n  Installed. Start Sandustry and press ^ (or F1) to open the console.')
  say('  Nothing in the game directory was modified.\n')
}

function uninstall() {
  const slot = resolveSlotDir()
  if (!slot || !fs.existsSync(slot)) { say('\n  Nothing to remove.\n'); return }
  try {
    fs.rmSync(slot, { recursive: true, force: true })
    say('\n  Removed ' + slot + '\n')
  } catch (e) {
    fail('could not remove ' + slot + ': ' + e.message)
  }
}

const arg = process.argv[2]
if (arg === '--status' || arg === '-s') status()
else if (arg === '--uninstall' || arg === '-u') uninstall()
else install()
